#!/bin/bash

RUN=0
BUILD=1
DEBUG=0
ASST=""

for VAR in "$@"
do
	if [[ "$VAR" = "-r" ]]; then
		RUN=1
	elif [[ "$VAR" = "-s" ]]; then
		BUILD=0
	elif [[ "$VAR" = "-d" ]]; then
		RUN=1
		DEBUG=1	
	else
		ASST=$VAR
	fi
done

if [[ -z "$ASST" ]]; then
	echo "Expects assignment number as parameter."
else
	if [[ "$BUILD" -eq 1 ]]; then
		echo "*** BUILDING ASST$ASST ***"
		(cd os161-1.11/kern/conf && ./config ASST$ASST)
		(cd os161-1.11/kern/compile/ASST$ASST && make clean)
		(cd os161-1.11/kern/compile/ASST$ASST && make depend)
		(cd os161-1.11/kern/compile/ASST$ASST && make)
		cp os161-1.11/kern/compile/ASST$ASST/kernel root/kernel-ASST$ASST
		
		if [[ "$RUN" -ne 0 && "$?" -ne 0 ]]; then
			echo "Build failed. Aborting run."
			RUN=0
		fi

		rm root/kernel
		(cd root && ln -s kernel-ASST$ASST kernel)
	fi

	if [[ "$RUN" -eq 1 ]]; then
		if [[ "$DEBUG" -eq 1 ]]; then
			(cd root && sys161 -w kernel)
		else
			(cd root && sys161 kernel)
		fi
	fi
fi
